### ISSUE TITLE
1.19 spigot服务端启动报错

### ISSUE THREAD

**Issue by elissa1997** [myunco/LiteItemShow#3]
## 系统信息
```bash
Centos 7

java version "17.0.3.1" 2022-04-22 LTS
Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)

nodejs v14.19.1
```

## 使用面板
MCSM 9.4.5

## 报错信息如下
```bash

[00:10:41] [Server thread/ERROR]: Could not load 'p1ugins/LiteItemShow-1.1.0.jar' in folder 'p1ugins'
org.bukkit.plugin.InvalidDeacriptionException: Invalid plugin.yml
    at org.bukkit.plugin. java.JavaPluginLoader.getPluginDescription (JavaPluginLoader. java:178) ~ [spigot-api-1.19-R0.1-SNAPSHOT.jar:2]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:143) ~ [gpigot-api-1.19-R0.1-SNAPSHOT.jar:2] 
    at org.bukkit.craftbukkit.v1_19 R1.CraftServer.loadPlugins(CraftServer. java:412) ~ [spigot-1.19-R01-SNAPSHOT. jar: 3550-Spigot-14a2382-9a8e080]
    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:224) ~ [spigot-1.19-R0.1-SNAPSHOT.jar :3550-Spigot-14a2382-9a8e080]
    at net.minecraft.server.MinecraftServer.V(MinecraftServer. java:966) ~ [ spigot-1.19-R0.1-SNAPSHOT. jar: 3550-Spigot -14a2382 -9a8e080]
    at net.minecraft.server.MinecraftServer.lambda$o (MinecraftServer.java:291) ~ [spigot-1.19-R0.1-SNAPSHOT. jar: 3550-Spigot 14a2382-9a8e080]
    at java.lang.Thread.run (Thread . java:833) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
    at java.util.zip.ZipFilesSource.findEND ( ZipFile. java:1469~[?:?]
    at java.util.zip.ZipFilesSource.initCEN ( ZipFile. java:1477) -[2:2]
    at java.util.zip.ZipFilesSource.<init> (ZipFile. java:1315) ~[2:2]
    at java.util.zip.ZipFilesSource.get (Z1pFi1e. java:1277) ~[?:?]
    at java.util.zip.ZipFiles$CleanableResource.<init> (ZipFile. java:709) ~[?:?]
    at java.util.zip.ZipFiles.<init> (ZipFile. java:243) ~[?:2]
    at java.util.zip.ZipFiles.<init> (ZipFile. java:172) ~[2:2]
    at java.util.jar.JarFile.<init> JarFile. java:347) ~[?:2]
    at java.util.jar.JarFile.<init> (JarFi1e. java:318) ~[?:?]
    at java.util.jar.JarFile..<init> (JarFile.java:284) ~[?:2]
    at org.bukkit.plugin.java.JavaPluginLoader getPluginDescription ( JavaPluginLoader. java:166) ~ [spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
6more
```

![~VT)`YWSL9S8$5VDL`D{9Z7](https://user-images.githubusercontent.com/25509920/179411227-d8e5c48b-7c95-4a5b-bfd9-84b1743ab7a7.png)

**Comment by myunco** [comment]
下载的插件损坏导致的，不是插件本身问题。
mcbbs下载经常出现这种情况，建议去百度网盘下载。

**Comment by elissa1997** [comment]
重新下载已经解决🎉
