### ISSUE TITLE
[更新希望]1.21无法运行

### ISSUE THREAD

**Issue by shawnlihst** [myunco/LiteItemShow#4]
[11:34:54 INFO]: [LiteItemShow] Enabling LiteItemShow v1.1.1
[11:34:54 INFO]: [LiteItemShow] minecraft version: 1.21
[11:34:54 WARN]: java.lang.StringIndexOutOfBoundsException: Range [23, 22) out of bounds for length 22
[11:34:54 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[11:34:54 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[11:34:54 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[11:34:54 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[11:34:54 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[11:34:54 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
[11:34:54 WARN]:        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
[11:34:54 WARN]:        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4861)
[11:34:54 WARN]:        at java.base/java.lang.String.substring(String.java:2830)
[11:34:54 WARN]:        at java.base/java.lang.String.substring(String.java:2803)
[11:34:54 WARN]:        at LiteItemShow-1.1.1.jar//ml.mcos.liteitemshow.nbt.NMS.<init>(NMS.java:21)
[11:34:54 WARN]:        at LiteItemShow-1.1.1.jar//ml.mcos.liteitemshow.LiteItemShow.onEnable(LiteItemShow.java:37)
[11:34:54 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[11:34:54 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[11:34:54 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[11:34:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[11:34:54 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643)
[11:34:54 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592)
[11:34:54 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:693)
[11:34:54 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:455)
[11:34:54 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361)
[11:34:54 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171)
[11:34:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[11:34:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:34:54 ERROR]: [LiteItemShow] 插件加载出错：不受支持的服务端版本

**Comment by Little100** [comment]
是的 我也无法使用 希望更新

**Comment by myunco** [comment]
最近时间不太够用，下个月我尽量抽时间看看

**Comment by Little100** [comment]
豪德感谢

**Comment by bluejt** [comment]
现在有更新到支持1.21或者更高版本吗

**Comment by Little100** [comment]
> 现在有更新到支持1.21或者更高版本吗

似乎还没有

**Comment by myunco** [comment]
由于mojang大改物品NBT，导致原有方法失效。目前暂未找到在1.20.5+版本中展示物品的方法，无法提供1.21支持。

**Comment by Little100** [comment]
我自己写了一个物品展示的插件 但肯定没大大写得好 所以只能凑合着用 在我主页找找 我现在在学校不好找链接 等作者出了最新版用大大的吧

**Comment by myunco** [comment]
已找到在Paper中正常展示物品的方法并基于Paper-1.21重写了本插件，名为LiteItemShowX，新版本将在明天上传。
新版本与旧版本的区别：
1.新版本只支持Paper系服务端，不支持Bukkit和Spigot
2.新版本不支持展示物品时含有其他文字，例如不支持发送 "看看我的[item]"，只有发送的消息和关键词完全匹配才能展示物品。
3.新版本支持自定义括号颜色、显示物品数量
4.新版本基于1.21开发，不再兼容低版本Minecraft
以下是默认的配置：
```
#显示手持物品的关键字
keyword: '[i]'
#是否显示物品数量 true=显示 false=不显示
showAmount: true
#括号颜色 RGB格式
sColor: '55FFFF'
#物品数量 x 颜色 RGB格式 ([石头 x64]的x)
xColor: 'FFAA00'
#物品数量 数字颜色 RGB格式 ([石头 x64]的64)
nColor: 'FFAA00'
```
效果图：
![20240908222034](https://github.com/user-attachments/assets/e86a8e3f-0008-4c62-be74-a07b4c01b825)

**Comment by myunco** [comment]
已上传 前往 https://github.com/myunco/LiteItemShowX/releases 下载
